use crate::pt::*;
use crate::token::*;

grammar;

pub Func: Func = {
    <e:Expression> => {
        Func { expr: e }
    },
}

Expression: Expression = {
    <FunctionCall> => <>,
    NormalExpr,
    ParenthesizedExpression,
}

FunctionCall: Expression = {
    <l:@L> <f:Expression> "(" ")" <r:@R> => {
        Expression {

        }
    }
}

NormalExpr: Expression = {
    "a" => {
        Expression {}
    }
}

ParenthesizedExpression: Expression = {
    "(" <e:Expression> ")" => e,
}

